version: '3.2'

services:
    code-server:
      image: linuxserver/code-server
      container_name: code-server
      environment:
        - PUID=1000
        - PGID=1000
        - TZ=Europe/London
        - SUDO_PASSWORD=password #optional
      volumes:
        - "./config:/config:ro"
      ports:
        - 8443:8443
      restart: unless-stopped